spring:
  security:
    user:
      name: username
      password: password
  application:
    name: rest-web-services
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  datasource:
#    url: jdbc:h2:mem:testdb
    url: "jdbc:mariadb://localhost:3306/attendance"
    username: attendance_admin
    password: user!@#
    driver-class-name: org.mariadb.jdbc.Driver
logging:
  level:
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
